### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by joonas** [skibblenybbles/PinterestPlus#1]
Hi Mike,

First off I wanted to thank you for writing this library, it's exactly what I was looking for after a couple rather frustrating attempts in trying to use the code provided by Pinterest in ways that it's not suited for.

Secondly, as the title implies, I'm curious about what kind of licensing were you thinking about releasing this under? I'd like to make use of it on a project I'm working on, license permitting of course.

BR,
Joonas

**Comment by skibblenybbles** [comment]
Hi Joonas,

I'm not particularly concerned about my intellectual property with this, as it's just a refactor and improvement of Pinterest's own code. I'm not familiar with all the ins and outs of the current licences, but my intention is to make this code totally free for anyone to use however they want, so long as they don't use it and then change the licensing to something less friendly. I would lean toward the Dojo framework's licensing approach: http://dojotoolkit.org/license, which is a modified BSD license or the Academic Free License version 2.1. This makes the code available for Open Source and commercial settings.

I would warn that it may be a little dangerous to use this library for production work, as the API endpoints that the code depends on are likely to change at some point, so please only use it at your own risk.

I hope this answers your question, and I'm excited that people in the community are taking interest in this project.

Best,
Mike

**Comment by skibblenybbles** [comment]
Joonas - I would also recommend watching julien-c's [Pinterest-Button-JavaScript repo](https://github.com/julien-c/Pinterest-Button-Javascript). He is tracking changes to the original pinit.js and is posting a beautified JavaScript file of the minified source. If you see the "pinit," "pinit_secure" or "button" configuration settings at the bottom of the file change, my script will break.

Mike

**Comment by joonas** [comment]
Hello Mike,

I'm glad to hear that you are leaning towards an open license like Dojo's, I'm personally a big fan of BSD licensing and the like, so that would be perfect. That more than answers my question.

I understand that there's the possibility that Pinterest may at any time change their API at their discretion, but it doesn't concern me as much as the horrible user experience that people would have to put up with if I were to use Pinterest's own library.

I'm hoping that Pinterest will eventually roll something like this (if not this) in to their own API so that it becomes more flexible to work with.

Thanks for pointing out julien-c's repo, I'll definitely start watching it for changes to keep myself up-to-date and fork + submit patches here should something change (and you don't get around to do it before me).

Thanks again for your work, it's much appreciated :)

BR,
Joonas

**Comment by chrishow** [comment]
I'd love to use this awesome bit of code in a project, but can't without an explicit licence and copyright notice due to my contract terms with the client. While your comment stating your intention is good enough for me, it's not good enough for the pencil-pushers.

I'm aware of the risks of Pinterest changing their API.

Any chance of adding an explicit licence file? 

BSD would be great for my purposes too. That or a note that it's in the public domain.

**Comment by skibblenybbles** [comment]
@chrishow - I added the FreeBSD license and also updated the README with the legalese. My hope is that this license is liberal enough for pretty much anyone's purposes.
