### ISSUE TITLE
Syntax for specifying element containing Pinterest button

### ISSUE THREAD

**Issue by andynash** [skibblenybbles/PinterestPlus#2]
First off, thanks a bunch for this! I am hoping to use it to avoid parsing multiple buttons in one go (a page will contain at least 20 items, each with a Pinterest button).

However, while I have the script working - PinterestPlus.pinit(); works fine - I cannot seem to get it focus on one particular element, and it is parsing them all with the performance impact I am hoping to avoid. I have tried:

PinterestPlus.pinit('class');
PinterestPlus.pinit('id');
PinterestPlus.pinit('div.id');
PinterestPlus.pinit('div.classname);
PinterestPlus.pinit(document.getElementById('id'));

where of course 'id' and 'class' are valid for the divs concerned.

How should I be defining the element?

Thanks!

Andy

**Comment by skibblenybbles** [comment]
Hi Andy,

The `pinit()` method only accepts a DOM node as an argument, not a CSS-style selector string. `pinit()` searches inside the passed DOM node for any Pinterest tags and converts them to `<iframe>`s similarly to the script provided by Pinterest.

My assumption is that most developers will group together social sharing buttons under a `<div>` with a specific class name and process all the buttons inside those `<div>`s at once. As an example, imagine you have a page with several social sharing blocks. Each block might look like:

```
<div class="social">
    <div class="facebook">
        <!-- Facebook button tag here -->
    </div>
    <div class="google">
        <!-- Google+ button tag here -->
    </div>
    <div class="pinterest">
        <!-- Pinterest button tag here -->
    </div>
</div>
```

With a framework like jQuery, your JavaScript could process each `<div class="social">` with some code like this:

```
$("div.social:not(.loaded)").each(function(node) {

    // mark this social <div> as loaded so it doesn't get processed again
    $(node).addClass("loaded");

    // process all of the sharing buttons inside this node
    FB.XFBML.parse(node);
    gapi.plusone.go(node);
    PinterestPlus.pinit(node);
});
```

In this example, the `loaded` class is used as a guard on the social `<div>`s to prevent them from being processed more than once.

The reason you can't pass a CSS-style selector string to `pinit()` is that PinterestPlus would need to implement all the complexities of a selector engine, and it would no longer be lightweight. The alternative is to make PinterestPlus depend on a particular JavaScript library like jQuery. It would be better to write a jQuery plugin that uses PinterestPlus as demonstrated in the example above.

I hope this helps. Let me know if you have questions or comments.

Best,
Mike

**Comment by andynash** [comment]
Thanks for the comprehensive reply Mike!

I thought I was completely misunderstanding things, but double-checked and discovered that the problem was in this line:

$("div.social:not(.loaded)").each(function(node) {

which should be:

$("div.social:not(.loaded)").each(function(index, node) {

Without that extra parameter, node is set to index.

This method does indeed work a little better - my previous method (passing an ID) was working for G+ and Facebook Likes, but not for Twitter or Pinterest.

Not only does this solve the Pinterest problem but it solves what I thought was an intractable problem with Twitter, so thanks!

Fyi, I ended up with the following function:

```
            function showButtons(elem) {
                    jQuery(elem+':not(.loaded)').each(function(index, node) {
                            jQuery(node).addClass("loaded");
                            FB.XFBML.parse(node);
                            gapi.plusone.go(node);
                            PinterestPlus.pinit(node);
                            twttr.widgets.load(node);
                    });
            };
```

**Comment by skibblenybbles** [comment]
HI Andy,

I'm glad you were able to build an elegant solution. Sorry about the jQuery bug. I've been using Dojo as my JavaScript library for a while now, so my jQuery is rusty. For fun, this is what your method would like as a Dojo package:

```
define(
    [
        "dojo/query",
        "dojo/dom-class"
    ],
    function(query, domClass) {

        return function(selector) {

            query(selector + ":not(.loaded)").forEach(function(node) {

                domClass.add(node, "loaded");
                FB.XFBML.parse(node);
                gapi.plusone.go(node);
                PinterestPlus.pinit(node);
                twttr.widgets.load(node);
            });
        }
    }
);
```

Best,
Mike
