### ISSUE TITLE
Change to Pinterest HTTP asset location

### ISSUE THREAD

**Issue by dinie** [skibblenybbles/PinterestPlus#3]
Hey there,
Firstly thanks for providing such a helpful piece of code.

Today I noticed that Pinterest have moved some of their assets to a different location, so my buttons weren't rendering at all. I went through your javascript and replaced this:
url:window.location.protocol==="https:"?"https://assets.pinterest.com/pinit.html":"http://pinit-cdn.pinterest.com/pinit.html"

With this:
url:window.location.protocol==="https:"?"https://assets.pinterest.com/pinit.html":"http://assets.pinterest.com/pinit.html"

I'm not sure if this is the best fix, but it works for now. Would like to know what you think

Cheers

**Comment by rwvandenberg** [comment]
Also observing this issue. 

I can confirm _dinie's_ fix works.

**Comment by skibblenybbles** [comment]
Thanks @dinie and @rwvandenberg for your help on this! Sorry it's taken me a while to look into this. I've updated the source and minified .js files with these changes.

**Comment by rwvandenberg** [comment]
You're quite welcome; thank you for making this available.
